In [3]:
import pandas as pd
import numpy as np
from scipy.spatial.distance import cdist

In [4]:
file_path = 'final_data 2.csv'
df = pd.read_csv(file_path)

In [23]:

# Get the values for row 300 
row300 = df.iloc[300][["pts", "ast", "reb"]]

# Get the selected columns from the entire dataframe  
stats = df[["pts", "ast", "reb"]]

# Use cdist to calculate euclidean distance  
dist = cdist(stats, row300.values.reshape(1, -1), metric='euclidean')

# dist array will contain the distances between row 300 and each row
print(dist)

[[6.20277357]
 [5.35687409]
 [4.81317982]
 ...
 [6.15801104]
 [7.25995179]
 [5.38744838]]


In [20]:
df = df.reset_index(drop=True)

In [6]:
df = df.select_dtypes(include=[np.number])

In [42]:
# Assuming 'dist' is your array of distances
sorted_indices = np.argsort(dist.flatten())  # Flatten and sort the indices based on distance

# Get the top 5 indices
top_5_indices = sorted_indices[:10]

# Print the indices and their corresponding distances
for i in top_5_indices:
    print(f"Row {i} - Distance: {dist[i]}")


Row 300 - Distance: [0.]
Row 372 - Distance: [0.96363894]
Row 30 - Distance: [1.23438244]
Row 361 - Distance: [1.5129772]
Row 179 - Distance: [1.52029602]
Row 931 - Distance: [1.67005988]
Row 231 - Distance: [1.68514094]
Row 353 - Distance: [1.76878489]
Row 326 - Distance: [1.84306809]
Row 308 - Distance: [1.91546339]


In [43]:

# Get the values for row 300 
row384 = df.iloc[384][["pts", "ast", "reb"]]

# Get the selected columns from the entire dataframe  
stats2 = df[["pts", "ast", "reb"]]

# Use cdist to calculate euclidean distance  
dist2 = cdist(stats2, row384.values.reshape(1, -1), metric='euclidean')

# dist array will contain the distances between row 300 and each row
print(dist2)

[[5.51553261]
 [2.52099187]
 [7.09470225]
 ...
 [4.89003067]
 [4.53464442]
 [5.54657552]]


In [44]:
# Assuming 'dist' is your array of distances
sorted_indices2 = np.argsort(dist2.flatten())  # Flatten and sort the indices based on distance

# Get the top 5 indices
top_5_indices2 = sorted_indices2[:10]

# Print the indices and their corresponding distances
for i in top_5_indices2:
    print(f"Row {i} - Distance: {dist2[i]}")


Row 384 - Distance: [0.]
Row 797 - Distance: [0.73885046]
Row 121 - Distance: [0.83162492]
Row 677 - Distance: [0.83480537]
Row 266 - Distance: [0.86994253]
Row 662 - Distance: [0.87344147]
Row 787 - Distance: [0.96524608]
Row 765 - Distance: [0.98645831]
Row 755 - Distance: [1.01877377]
Row 923 - Distance: [1.02254584]


In [45]:

# Get the values for row 300 
row384 = df.iloc[384][["pts", "ast", "reb", "fg_pct", "fg3_pct", "ft_pct", "fgm", "fg3m", "ftm"]]

# Get the selected columns from the entire dataframe  
stats3 = df[["pts", "ast", "reb", "fg_pct", "fg3_pct", "ft_pct", "fgm", "fg3m", "ftm"]]

# Use cdist to calculate euclidean distance  
dist3 = cdist(stats3, row384.values.reshape(1, -1), metric='euclidean')

# dist array will contain the distances between row 300 and each row
print(dist3)

[[6.24047025]
 [3.10333788]
 [7.26991369]
 ...
 [5.36977411]
 [5.04529097]
 [5.65909657]]


In [46]:
# Assuming 'dist' is your array of distances
sorted_indices3 = np.argsort(dist3.flatten())  # Flatten and sort the indices based on distance

# Get the top 5 indices
top_5_indices3 = sorted_indices3[:10]

# Print the indices and their corresponding distances
for i in top_5_indices3:
    print(f"Row {i} - Distance: {dist3[i]}")


Row 384 - Distance: [0.]
Row 765 - Distance: [1.29354938]
Row 332 - Distance: [1.31105339]
Row 797 - Distance: [1.34711915]
Row 662 - Distance: [1.58486592]
Row 445 - Distance: [1.62206196]
Row 787 - Distance: [1.63321952]
Row 346 - Distance: [1.70070191]
Row 975 - Distance: [1.72639538]
Row 638 - Distance: [1.78213973]


In [7]:
# Get the values for row 300 
row195 = df.iloc[195][["reb", "blk"]]

# Get the selected columns from the entire dataframe  
stats4 = df[["reb", "blk"]]

# Use cdist to calculate euclidean distance  
dist4 = cdist(stats4, row195.values.reshape(1, -1), metric='euclidean')

# dist array will contain the distances between row 300 and each row
print(dist4)

[[2.22766694]
 [3.69579491]
 [4.38041094]
 ...
 [2.39207023]
 [1.88663722]
 [2.41960741]]


In [8]:
# Assuming 'dist' is your array of distances
sorted_indices4 = np.argsort(dist4.flatten())  # Flatten and sort the indices based on distance

# Get the top 5 indices
top_5_indices4 = sorted_indices4[:10]

# Print the indices and their corresponding distances
for i in top_5_indices4:
    print(f"Row {i} - Distance: {dist4[i]}")


Row 195 - Distance: [0.]
Row 801 - Distance: [0.02236068]
Row 540 - Distance: [0.07211103]
Row 818 - Distance: [0.09899495]
Row 227 - Distance: [0.1]
Row 10 - Distance: [0.1]
Row 933 - Distance: [0.12041595]
Row 235 - Distance: [0.14866069]
Row 561 - Distance: [0.14866069]
Row 940 - Distance: [0.15231546]
